yarnPath: .yarn/releases/yarn-3.2.0.cjs

packageExtensions:
  # awaiting fix: https://github.com/facebook/create-react-app/issues/11982
  "eslint-plugin-flowtype@*":
    peerDependenciesMeta:
      "@babel/plugin-syntax-flow":
        optional: true
      "@babel/plugin-transform-react-jsx":
        optional: true

  # awaiting fix: https://github.com/facebook/create-react-app/pull/11526
  "react-dev-utils@*":
    peerDependencies:
      "typescript": ">=2.7"
      "webpack": ">=4"
